In [30]:
import pandas as pd

In [31]:
df = pd.read_csv('GWS_no_soil.csv')

In [32]:
#This code calculates the average storage for each year, computes the difference between consecutive years, 
#and then calculates the average of these differences to obtain the average annual change in groundwater storage. 
#The result is then added to the DataFrame as a new column called 'average_annual_change'.

In [33]:
# Calculate the average annual change in groundwater storage
storage_columns = [col for col in df.columns if col not in ['lat', 'lon']]
years = list(set([col.split('-')[0] for col in storage_columns]))
years.sort()

annual_changes = []

In [34]:
for year in years[:-1]:
    next_year = str(int(year) + 1)
    year_columns = [col for col in storage_columns if col.startswith(year)]
    next_year_columns = [col for col in storage_columns if col.startswith(next_year)]

    year_storage = df[year_columns].mean(axis=1)
    next_year_storage = df[next_year_columns].mean(axis=1)

    annual_change = next_year_storage - year_storage
    annual_changes.append(annual_change)

average_annual_change = pd.concat(annual_changes, axis=1).mean(axis=1)

# Add the average annual change to the DataFrame
df['average_annual_change'] = average_annual_change

df.to_csv('GWS_no_soil_AAC.csv', index=None)

In [35]:
df = pd.read_csv('GWS.csv')

In [36]:
#This code calculates the average storage for each year, computes the difference between consecutive years, 
#and then calculates the average of these differences to obtain the average annual change in groundwater storage. 
#The result is then added to the DataFrame as a new column called 'average_annual_change'.

In [37]:
# Calculate the average annual change in groundwater storage
storage_columns = [col for col in df.columns if col not in ['lat', 'lon']]
years = list(set([col.split('-')[0] for col in storage_columns]))
years.sort()

annual_changes = []

In [38]:
for year in years[:-1]:
    next_year = str(int(year) + 1)
    year_columns = [col for col in storage_columns if col.startswith(year)]
    next_year_columns = [col for col in storage_columns if col.startswith(next_year)]

    year_storage = df[year_columns].mean(axis=1)
    next_year_storage = df[next_year_columns].mean(axis=1)

    annual_change = next_year_storage - year_storage
    annual_changes.append(annual_change)

average_annual_change = pd.concat(annual_changes, axis=1).mean(axis=1)

# Add the average annual change to the DataFrame
df['average_annual_change'] = average_annual_change

df.to_csv('GWS_AAC.csv', index=None)

In [39]:
df = pd.read_csv('recharge_with_coord.csv')

In [40]:
#This code calculates the average storage for each year, computes the difference between consecutive years, 
#and then calculates the average of these differences to obtain the average annual change in groundwater storage. 
#The result is then added to the DataFrame as a new column called 'average_annual_change'.

In [41]:
# Calculate the average annual change in groundwater storage
storage_columns = [col for col in df.columns if col not in ['lat', 'lon']]
years = list(set([col.split('-')[0] for col in storage_columns]))
years.sort()

annual_changes = []

In [43]:
for year in years[:-1]:
    next_year = str(int(year) + 1)
    year_columns = [col for col in storage_columns if col.startswith(year)]
    next_year_columns = [col for col in storage_columns if col.startswith(next_year)]

    year_storage = df[year_columns].mean(axis=1)
    next_year_storage = df[next_year_columns].mean(axis=1)

    annual_change = next_year_storage - year_storage
    annual_changes.append(annual_change)

average_annual_change = pd.concat(annual_changes, axis=1).mean(axis=1)

# Add the average annual change to the DataFrame
df['average_annual_change'] = average_annual_change

df.to_csv('recharge_with_coord_AAC.csv', index=None)
df

,lat,lon,2003-01-15 00:00:00,2003-02-15 00:00:00,2003-03-15 00:00:00,2003-04-15 00:00:00,2003-05-15 00:00:00,2003-06-15 00:00:00,2003-07-15 00:00:00,2003-08-15 00:00:00,...,2014-04-15 00:00:00,2014-05-15 00:00:00,2014-06-15 00:00:00,2014-07-15 00:00:00,2014-08-15 00:00:00,2014-09-15 00:00:00,2014-10-15 00:00:00,2014-11-15 00:00:00,2014-12-15 00:00:00,average_annual_change
0,27.875,31.375,0.117917,0.037445,0.031139,0.043059,0.032451,0.029778,0.037662,0.036935,...,0.379790,0.405382,0.240707,0.180818,0.159148,0.116869,0.098342,0.080150,0.074325,0.010771
1,27.875,31.625,0.176378,0.053420,0.045770,0.055883,0.042992,0.037316,0.042863,0.041273,...,0.533836,0.491260,0.294883,0.219995,0.185947,0.137381,0.114908,0.092752,0.088661,0.013611
2,27.875,31.875,0.343629,0.099991,0.114001,0.117078,0.086958,0.070166,0.067739,0.066843,...,0.817113,0.678292,0.438936,0.320214,0.256335,0.193181,0.157218,0.123750,0.128051,0.019938
3,27.875,32.125,0.455442,0.133010,0.208234,0.227642,0.158476,0.124347,0.115224,0.125963,...,1.082211,0.958502,0.636234,0.460764,0.374898,0.286763,0.224327,0.171804,0.179135,0.029249
4,27.875,32.375,0.595644,0.170978,0.339615,0.378077,0.250854,0.193142,0.188029,0.208003,...,1.572195,1.392986,0.914512,0.657371,0.550678,0.423360,0.317829,0.237099,0.250603,0.044803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6197,51.125,18.875,96.772988,17.815239,8.175088,4.063623,10.163427,5.627854,8.971266,23.774272,...,7.658954,25.261906,30.419326,25.358789,23.206425,33.970875,17.328129,19.246850,23.034309,0.392790
6198,51.125,19.125,95.641839,17.821400,7.917759,3.992385,11.383339,5.881222,8.833718,25.173555,...,7.847368,26.451429,31.853587,22.400234,25.058814,29.865191,16.255366,17.473019,22.845805,0.359174
6199,51.125,19.375,94.408325,17.906836,7.871176,4.053029,13.688114,6.546657,9.045713,27.414889,...,8.444328,30.701040,36.200521,21.769083,29.648357,28.456392,16.046104,16.195221,22.800258,0.411515
6200,51.125,19.625,93.194514,17.787481,7.588753,3.962250,12.570707,6.247813,8.479983,27.482020,...,8.822248,34.465160,33.813831,21.105550,32.927236,27.205586,15.763117,15.480643,22.153199,0.428842
6201,51.125,19.875,92.001383,17.500665,7.089419,3.788899,8.730490,5.506353,7.770480,24.997932,...,9.029115,37.132975,27.102432,20.352763,33.277842,24.227950,14.918136,15.490322,20.843987,0.390183

In [76]:
import pandas as pd


df =  pd.read_csv('GWS_no_soil.csv')